# Generated by Django 2.0.12 on 2019-04-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('organic', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('bacon', models.BooleanField(default=False)),
                ('cheese', models.BooleanField(default=False)),
                ('steaks', models.SmallIntegerField(default=0)),
                ('others', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('organic', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('alcohol', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('organic', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burgers', models.ManyToManyField(blank=True, to='pizza.Burger')),
                ('drinks', models.ManyToManyField(blank=True, to='pizza.Drink')),
                ('meals', models.ManyToManyField(blank=True, to='pizza.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_on', models.DateTimeField(auto_now_add=True)),
                ('shipped_on', models.DateTimeField(auto_now_add=True)),
                ('burgers', models.ManyToManyField(blank=True, to='pizza.Burger')),
                ('drinks', models.ManyToManyField(blank=True, to='pizza.Drink')),
                ('meals', models.ManyToManyField(blank=True, to='pizza.Meal')),
                ('menus', models.ManyToManyField(blank=True, to='pizza.Menu')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('organic', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('calzone', models.BooleanField(default=False)),
                ('diameter', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('organic', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizza.Topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='pizza.Pizza'),
        ),
        migrations.AddField(
            model_name='menu',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='pizza.Pizza'),
        ),
    ]
